### ISSUE TITLE
Batch process

### ISSUE THREAD

**Issue by Ruke805** [oseiskar/autosubsync#10]
Is there a way to run in batch mode? For example, sync all files in a folder?

**Comment by oseiskar** [comment]
There's no built-in batch mode but you can use the Python API or a scripting language of your choice to create one. Here's a simple example (save as `batch_sync.py`)
```python
"""
Batch synchronize all video files in a folder. Usage:

    python batch_sync.py /path/to/folder
    
"""
import autosubsync
import glob
import os
import sys

target_folder = sys.argv[1]
# change this for other extensions than .mp4
VIDEO_EXT = 'mp4'

for video_file in glob.glob(os.path.join(target_folder, '*.' + VIDEO_EXT)):
    base = video_file.rpartition('.')[0]
    srt_file = base + '.srt'
    synced_srt_file = base + '_synced.srt'
    print('syncing ' + video_file)
    autosubsync.synchronize(video_file, srt_file, synced_srt_file)
```

**Comment by Ruke805** [comment]
Hi, thank you for the quick reply and for this great tool.

I'm not a programmer, so I don't have some skills. I did as you said, I've saved the script as batch_sync.py, and first I just changed the video format, I used mkv. When I ran the script in the same folder with all files I got this error:

```
Traceback (most recent call last):
  File "batch_sync.py", line 12, in <module>
    target_folder = sys.argv[1]
IndexError: list index out of range
```

So I thought could be the line "python batch_sync.py /path/to/folder", so I replaced the `"/path/to/folder"` to the path of the videos and subs, When I run this way, I got a new message error: 

```
File "batch_sync.py", line 6
    """
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 84-85: malformed \N character escape
```
Am I doing something wrong? Sorry if this is a dumb question, I have little knowledge of programming.

Edit. I'm on windows 10, if this is important

**Comment by oseiskar** [comment]
Both things, `mp4` -> `mkv` & replacing the placeholder `/path/to/folder`, are correct, but I guess you may have hit the (stupid) problem of Windows, Unix and Mac using different types of newline characters so you should have used a different text editor, e.g., Atom or Notepad++ to edit the file.

(To check if this was the case, just try again with this version which already has `mkv`):

```python
"""
Batch synchronize all video files in a folder. Usage:

    python batch_sync.py /path/to/folder
    
"""
import autosubsync
import glob
import os
import sys

target_folder = sys.argv[1]
# change this for other extensions than .mp4
VIDEO_EXT = 'mkv'

for video_file in glob.glob(os.path.join(target_folder, '*.' + VIDEO_EXT)):
    base = video_file.rpartition('.')[0]
    srt_file = base + '.srt'
    synced_srt_file = base + '_synced.srt'
    print('syncing ' + video_file)
    autosubsync.synchronize(video_file, srt_file, synced_srt_file)
```

**Comment by Ruke805** [comment]
Thank you for the reply. I've tried this new script, seems to start sync well.. it appears the message `syncing C:\path\video.mkv`, but after some seconds, show me this error: 

The script starts a loop and never stops
```
Traceback (most recent call last):
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\site-packages\autosubsync\features.py", line 71, in maybe_parallel_map
    pool = Pool(parallelism)
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\valbe\Desktop\,,\batch_sync.py", line 21, in <module>
    autosubsync.synchronize(video_file, srt_file, synced_srt_file)
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\site-packages\autosubsync\main.py", line 75, in synchronize
    features_x, shifted_y = features.compute(sound_data, subvec, parallelism=parallelism)
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\site-packages\autosubsync\features.py", line 99, in compute
    all_x = np.vstack(maybe_parallel_map(_compute_chunk_features_star, data_chunks, parallelism))
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\site-packages\autosubsync\features.py", line 74, in maybe_parallel_map
    pool.close()
UnboundLocalError: local variable 'pool' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\site-packages\autosubsync\features.py", line 71, in maybe_parallel_map
    pool = Pool(parallelism)
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\valbe\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

**Comment by oseiskar** [comment]
Ok. Strange Windows-specific issue. Try this:
```python
"""
Batch synchronize all video files in a folder. Usage:

    python batch_sync.py /path/to/folder

"""
import autosubsync
import glob
import os
import sys

if __name__ == '__main__':
    target_folder = sys.argv[1]
    # change this for other extensions than .mp4
    VIDEO_EXT = 'mkv'

    for video_file in glob.glob(os.path.join(target_folder, '*.' + VIDEO_EXT)):
        base = video_file.rpartition('.')[0]
        srt_file = base + '.srt'
        synced_srt_file = base + '_synced.srt'
        print('syncing ' + video_file)
        autosubsync.synchronize(video_file, srt_file, synced_srt_file)
```

**Comment by Ruke805** [comment]
Thank you! Now worked very well. 
Thank you so much for your help. Success in your career!
