### ISSUE TITLE
Bug with anaconda

### ISSUE THREAD

**Issue by ghost** [oseiskar/autosubsync#13]
Hi, I try to install and execute in anaconda.

I have this error:

`FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  subvec = np.zeros(n, np.bool)
Traceback (most recent call last):
  File "C:\Users\Gabriel\anaconda3\envs\whisper\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Gabriel\anaconda3\envs\whisper\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gabriel\anaconda3\envs\whisper\Scripts\autosubsync.exe\__main__.py", line 7, in <module>
  File "C:\Users\Gabriel\anaconda3\envs\whisper\lib\site-packages\autosubsync\main.py", line 147, in cli_packaged
    cli(packaged_model=True)
  File "C:\Users\Gabriel\anaconda3\envs\whisper\lib\site-packages\autosubsync\main.py", line 134, in cli
    success = synchronize(args.video_file, args.subtitle_file, args.output_file,\
  File "C:\Users\Gabriel\anaconda3\envs\whisper\lib\site-packages\autosubsync\main.py", line 70, in synchronize
    sound_data, subvec = preprocessing.import_target_files(video_file, subtitle_file)
  File "C:\Users\Gabriel\anaconda3\envs\whisper\lib\site-packages\autosubsync\preprocessing.py", line 89, in import_target_files
    return import_item(sound_file, subtitle_file, **kwargs)
  File "C:\Users\Gabriel\anaconda3\envs\whisper\lib\site-packages\autosubsync\preprocessing.py", line 59, in import_item
    sub_vec = import_subs(subtitle_file, sample_rate, n, **kwargs)
  File "C:\Users\Gabriel\anaconda3\envs\whisper\lib\site-packages\autosubsync\preprocessing.py", line 53, in import_subs
    return build_sub_vec(subs, sample_rate, n, **kwargs)
  File "C:\Users\Gabriel\anaconda3\envs\whisper\lib\site-packages\autosubsync\preprocessing.py", line 34, in build_sub_vec
    subvec = np.zeros(n, np.bool)
  File "C:\Users\Gabriel\anaconda3\envs\whisper\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations`

do you Have some idea for how i can solve it?

**Comment by oseiskar** [comment]
Thank you for reporting. This was indeed broken with newer Numpy versions. Should now be fixed in version 1.0.1, which I just pushed to PyPI: https://pypi.org/project/autosubsync/1.0.1/
