### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by potapenko** [oseiskar/autosubsync#8]
```
Extracting audio using ffmpeg and reading subtitles...
computing features for 116945579 audio samples using 3 parallel process(es)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autosubsync/features.py", line 84, in _compute_chunk_features_star
    return compute_chunk_features(*args)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autosubsync/features.py", line 80, in compute_chunk_features
    spectra = compute_spectra(apply_windowing(training_x)/float(data_range), 3*frame_secs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autosubsync/features.py", line 43, in compute_spectra
    spectrum = np.abs(np.fft.rfft(windowed, axis=1))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/mkl_fft/_numpy_fft.py", line 335, in rfft
    output = mkl_fft.rfft_numpy(x, n=n, axis=axis)
  File "mkl_fft/_pydfti.pyx", line 609, in mkl_fft._pydfti.rfft_numpy
  File "mkl_fft/_pydfti.pyx", line 521, in mkl_fft._pydfti._rc_fft1d_impl
ValueError: Internal error occurred: b'Intel MKL DFTI ERROR: Inconsistent configuration parameters'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/autosubsync", line 10, in <module>
    sys.exit(cli_packaged())
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autosubsync/main.py", line 147, in cli_packaged
    cli(packaged_model=True)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autosubsync/main.py", line 139, in cli
    fixed_skew = args.fixed_skew)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autosubsync/main.py", line 75, in synchronize
    features_x, shifted_y = features.compute(sound_data, subvec, parallelism=parallelism)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autosubsync/features.py", line 99, in compute
    all_x = np.vstack(maybe_parallel_map(_compute_chunk_features_star, data_chunks, parallelism))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autosubsync/features.py", line 72, in maybe_parallel_map
    return pool.map(f, data)
  File "/usr/local/anaconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: Internal error occurred: b'Intel MKL DFTI ERROR: Inconsistent configuration parameters'
```

**Comment by potapenko** [comment]
I solved it by reinstalling numpy (1.18.0)
